### ISSUE TITLE
Integrating new FinetuningModel class

### ISSUE THREAD

**Issue by WenkelF** [WenkelF/graphium#2]
A flexible class that consists of two parts:
1. Pretrained module (of class FullGraphMultitaskNetwork and potentially more flexibility)
2. Finetuning module (any network that is compatible with the pretrained module)

What to look out for:
- Want to be able to (un)freeze every part of the model
- Ability to read out intermediate outputs (for featurization)
- Finetune module must suport different input/output levels

Here are Andy's Diagrams illustrating two possible scenarios:
![finetune_from_GNN](https://github.com/WenkelF/graphium/assets/45903652/66858d73-b32e-4423-a96e-429431729aa1)
![finetune_from_task](https://github.com/WenkelF/graphium/assets/45903652/49a8e390-21a4-4902-8098-9a12a7fbfbd5)

**Comment by engmubarak48** [comment]
1. Freezing of the weights
2. Unfreeze the weights, i.e. fine-tuning from GNNs layers, Layer-wise MLPs,  and Tasks heads. 
3. Check the weights are loaded correctly for the fine-tuning path
4. Decide which layer to get output from. e.g. use the last 5 layers of GNNs. 
5. Check the finetune Head module works correctly. I.e. it is able to get the correct embedding from the chosen layer. 
6. Ensure the optimizer is updated accordingly and is working correctly. The optimizer could have different hyper-parameters 
7. Run the final experiment to validate everything works. e.g. use TDC for fine-tuning
8. For performance analysis, compare frozen and unfrozen weights. 
9. Check the literature for fine-tuning of GNNs. Are there hacks? 
10. For the future, epoch-wise fine-tuning, for instance only finetune for 2 epochs.
